import dots from "./dots.png"
import deleteIcon from "./delete.png"
import edit from "./edit.png"
import add from "./add.png"
import logout from "./logout.png"
import time from "./time.png"
import countdown from "./countdown.png"
import stopwatch from "./stopwatch.png"
import todo from "./todo.png"
import setting from "./setting.png"
import notes from "./notes.png"
export {dots,deleteIcon,edit,add,logout,time,countdown,stopwatch,todo,setting,notes}